- name: Build Single Node Kubernetes Cluster on Fedora
  hosts: k8s_nodes
  become: true
  vars:
    k8s_version: "1.32"
    k8s_patch_version: "1.32.0"
    pod_subnet: "10.244.0.0/16"

  pre_tasks:
    - name: Wait for SSH connection to be available
      ansible.builtin.wait_for_connection:
        delay: 5
        timeout: 300

    - name: Wait for Cloud-Init to complete (File check)
      ansible.builtin.wait_for:
        path: /var/lib/cloud/instance/boot-finished
        state: present
        timeout: 300

  tasks:
    - name: Install ethtool
      ansible.builtin.dnf:
        name: ethtool
        state: present

    - name: Disable TCP segmentation offload to prevent packet drops
      ansible.builtin.shell: |
        for iface in $(ls /sys/class/net/ | grep -E '^(eth|ens|enp)'); do
          ethtool -K $iface tx off sg off tso off gro off gso off || true
        done
      changed_when: false

    - name: Configure NetworkManager to ignore Calico interfaces
      ansible.builtin.copy:
        dest: /etc/NetworkManager/conf.d/calico.conf
        content: |
          [keyfile]
          unmanaged-devices=interface-name:cali*;interface-name:tunl*;interface-name:vxlan.calico;interface-name:wireguard.cali
      notify: Reload NetworkManager

    - name: Disable Swap (runtime)
      ansible.builtin.command: swapoff -a
      changed_when: false

    - name: Disable Swap (permanent in fstab)
      ansible.builtin.replace:
        path: /etc/fstab
        regexp: '^([^#].*swap.*)$'
        replace: '# \1'

    - name: Remove zram packages (Fedora specific)
      ansible.builtin.dnf:
        name:
          - zram-free-utils
          - zram-generator-defaults
        state: absent

    - name: Load Kernel Modules
      community.general.modprobe:
        name: "{{ item }}"
        state: present
      loop:
        - overlay
        - br_netfilter

    - name: Persist Kernel Modules
      ansible.builtin.copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          overlay
          br_netfilter

    - name: Configure Sysctl
      ansible.posix.sysctl:
        name: "{{ item.key }}"
        value: "{{ item.value }}"
        sysctl_set: yes
        state: present
        reload: yes
      loop:
        - { key: 'net.bridge.bridge-nf-call-iptables', value: '1' }
        - { key: 'net.bridge.bridge-nf-call-ip6tables', value: '1' }
        - { key: 'net.ipv4.ip_forward', value: '1' }

    - name: Set SELinux to Permissive
      ansible.posix.selinux:
        policy: targeted
        state: permissive

    - name: Install firewalld packages
      ansible.builtin.dnf:
        name:
          - firewalld
          - python3-firewall
        state: present

    - name: Ensure Firewalld is running
      ansible.builtin.systemd:
        name: firewalld
        enabled: yes
        state: started

    - name: Fix broken default zone (Force set to public)
      ansible.builtin.command: firewall-cmd --set-default-zone=public
      changed_when: false

    - name: Configure Firewalld Ports
      ansible.posix.firewalld:
        zone: public
        port: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: yes
      loop:
        - 6443/tcp
        - 10250/tcp
        - 2379-2380/tcp
        - 179/tcp
        - 4789/udp

    - name: Trust Pod Network (Allow Pod-to-Pod communication)
      ansible.posix.firewalld:
        zone: trusted
        source: "{{ pod_subnet }}"
        permanent: yes
        state: enabled
        immediate: yes

    - name: Reload Firewalld to apply changes
      ansible.builtin.command: firewall-cmd --reload
      changed_when: false

    - name: Install CRI-O
      ansible.builtin.dnf:
        name: cri-o
        state: present

    - name: Enable CRI-O
      ansible.builtin.systemd:
        name: crio
        enabled: yes
        state: started

    - name: Add Kubernetes Repo
      ansible.builtin.yum_repository:
        name: kubernetes
        description: Kubernetes
        baseurl: "https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/rpm/"
        gpgcheck: yes
        gpgkey: "https://pkgs.k8s.io/core:/stable:/v{{ k8s_version }}/rpm/repodata/repomd.xml.key"
        enabled: yes

    - name: Install Kube tools and Helm dependencies
      ansible.builtin.dnf:
        name:
          - kubelet
          - kubeadm
          - kubectl
          - helm
          - python3-kubernetes
        state: present

    - name: Enable Kubelet
      ansible.builtin.systemd:
        name: kubelet
        enabled: yes

    - name: Check if cluster is already initialized
      ansible.builtin.stat:
        path: /etc/kubernetes/admin.conf
      register: kube_conf

    - name: Generate kubeadm config
      ansible.builtin.copy:
        dest: /root/kubeadm-config.yaml
        content: |
          apiVersion: kubeadm.k8s.io/v1beta4
          kind: InitConfiguration
          nodeRegistration:
            criSocket: "unix:///var/run/crio/crio.sock"
          ---
          apiVersion: kubeadm.k8s.io/v1beta4
          kind: ClusterConfiguration
          kubernetesVersion: "v{{ k8s_patch_version }}"
          networking:
            podSubnet: "{{ pod_subnet }}"
          ---
          apiVersion: kubelet.config.k8s.io/v1beta1
          kind: KubeletConfiguration
          cgroupDriver: "systemd"
      when: not kube_conf.stat.exists

    - name: Initialize Kubernetes Cluster
      ansible.builtin.command: kubeadm init --config /root/kubeadm-config.yaml
      when: not kube_conf.stat.exists
      register: kubeadm_init

    - name: Setup kubeconfig for root
      ansible.builtin.shell: |
        mkdir -p $HOME/.kube
        cp -f /etc/kubernetes/admin.conf $HOME/.kube/config
        chown $(id -u):$(id -g) $HOME/.kube/config

    - name: Install Calico Operator
      ansible.builtin.command: kubectl apply --server-side -f https://raw.githubusercontent.com/projectcalico/calico/v3.29.1/manifests/tigera-operator.yaml
      ignore_errors: true

    - name: Create Calico Custom Resources with Interface Config
      ansible.builtin.copy:
        dest: /root/custom-resources.yaml
        content: |
          apiVersion: operator.tigera.io/v1
          kind: Installation
          metadata:
            name: default
          spec:
            calicoNetwork:
              nodeAddressAutodetectionV4:
                interface: "en.*|eth.*"
              ipPools:
              - name: default-ipv4-ippool
                blockSize: 26
                cidr: "{{ pod_subnet }}"
                encapsulation: VXLANCrossSubnet
                natOutgoing: Enabled
                nodeSelector: all()
          ---
          apiVersion: operator.tigera.io/v1
          kind: APIServer
          metadata:
            name: default
          spec: {}

    - name: Apply Calico Custom Resources
      ansible.builtin.command: kubectl apply -f /root/custom-resources.yaml

    - name: Delete existing cni0 interface to force recreation
      ansible.builtin.shell: |
        if ip link show cni0 > /dev/null 2>&1; then
          ip link delete cni0
        fi
      ignore_errors: true

    - name: Restart Calico Pods to apply interface changes
      ansible.builtin.shell: |
        kubectl delete pods -n calico-system --all --force --grace-period=0
      ignore_errors: true

    - name: Wait for Node to be Ready
      ansible.builtin.command:
        cmd: kubectl wait --for=condition=Ready node --all --timeout=600s
      changed_when: false

    - name: Wait for Calico Pods to be Ready
      ansible.builtin.command:
        cmd: kubectl wait --for=condition=Ready pods --all -n calico-system --timeout=600s
      changed_when: false
      register: calico_wait
      until: calico_wait.rc == 0
      retries: 30
      delay: 10

    - name: Wait for CoreDNS to be Ready
      ansible.builtin.command:
        cmd: kubectl wait --for=condition=Ready pods -l k8s-app=kube-dns -n kube-system --timeout=600s
      changed_when: false

    - name: Remove Taint for Single Node
      ansible.builtin.command: kubectl taint nodes --all node-role.kubernetes.io/control-plane-
      register: taint_result
      failed_when:
        - "'not found' not in taint_result.stderr"
        - "taint_result.rc != 0"

    - name: Add ArgoCD Helm Repo
      kubernetes.core.helm_repository:
        name: argo
        repo_url: "https://argoproj.github.io/argo-helm"

    - name: Install ArgoCD via Helm
      kubernetes.core.helm:
        name: argocd
        chart_ref: argo/argo-cd
        release_namespace: argocd
        create_namespace: true
        values:
          server:
            extraArgs: []
              # - --insecure
            service:
              type: LoadBalancer
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

    - name: Add MetalLB Helm Repo
      kubernetes.core.helm_repository:
        name: metallb
        repo_url: "https://metallb.github.io/metallb"

    - name: Install MetalLB via Helm
      kubernetes.core.helm:
        name: metallb
        chart_ref: metallb/metallb
        release_namespace: metallb-system
        create_namespace: true
        wait: true
        timeout: 10m0s
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

    - name: Pause for MetalLB Webhook service to be ready
      ansible.builtin.pause:
        seconds: 30

    - name: Create MetalLB Configuration (IP Pool & L2 Advertisement)
      ansible.builtin.copy:
        dest: /root/metallb-config.yaml
        content: |
          apiVersion: metallb.io/v1beta1
          kind: IPAddressPool
          metadata:
            name: first-pool
            namespace: metallb-system
          spec:
            addresses:
            - {{ metallb_ip_range | default('10.0.0.100-10.0.0.200') }}
          ---
          apiVersion: metallb.io/v1beta1
          kind: L2Advertisement
          metadata:
            name: l2-advert
            namespace: metallb-system
          spec:
            ipAddressPools:
            - first-pool

    - name: Apply MetalLB Configuration
      ansible.builtin.command: kubectl apply -f /root/metallb-config.yaml
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

    - name: Add Ingress NGINX Helm Repo
      kubernetes.core.helm_repository:
        name: ingress-nginx
        repo_url: "https://kubernetes.github.io/ingress-nginx"

    - name: Install Ingress NGINX via Helm
      kubernetes.core.helm:
        name: ingress-nginx
        chart_ref: ingress-nginx/ingress-nginx
        release_namespace: ingress-nginx
        create_namespace: true
        values:
          controller:
            service:
              type: LoadBalancer
            watchIngressWithoutClass: true
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

    - name: Apply ArgoCD Bootstrap Application (App of Apps)
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('url', 'https://raw.githubusercontent.com/t0m0h1des-homelab/homelab-k8s-apps/main/argocd/bootstrap.yaml', split_lines=False) }}"
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf

  handlers:
    - name: Reload NetworkManager
      ansible.builtin.systemd:
        name: NetworkManager
        state: reloaded
